server {
    listen       80;
    server_name  localhost;

    location / {
        root   html/CampusIdlePlatform;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location /CampusIdlePlatform/ {
        root   html;
        index  index.html;
        try_files $uri $uri/ /CampusIdlePlatform/index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}
